title: stress-meowt
tagline: A brand new course on Learning Lab
description: asd
template:
  repo: stress-meowt-template
  name: stress-meowt
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
